#!/usr/bin/env bash
set -euo pipefail

echo "=== Pre-Publish Checklist ==="
echo ""

echo "1. Verify all tests pass:"
echo "   bun run test"
echo ""
echo "2. Verify type safety:"
echo "   bun run check-types"
echo ""
echo "3. Verify lint passes:"
echo "   bun run lint"
echo ""
echo "4. Verify build is clean:"
echo "   bun run build"
echo ""
echo "5. Verify coverage meets thresholds:"
echo "   bun run test:coverage"
echo ""
echo "6. Run the full verification script:"
echo "   bash scripts/verify-build.sh"
echo ""
echo "7. Check CHANGELOG.md is up to date"
echo ""
echo "8. Check version in package.json is correct"
echo ""
echo "9. Dry-run publish to inspect tarball:"
echo "   npm pack --dry-run"
echo ""
echo "10. Publish:"
echo "    npm publish --access public"
echo ""
echo "=== Ready for publish? ==="
